title: Lumiereva
description: >-
  A personal journal by Lumiereva — exploring life, words and light.
baseurl: "/-lumiereva-blog"
url: "https://xinyancai9-maker.github.io"

theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: auto

header_pages:
  - about.md
  - posts.md
